root = "."
tmp_dir = "build"

[build]
  args_bin = []
  bin = "./build/go-boilerplate-rest"
  cmd = "make build-rest"
  delay = 500
  rerun_delay = 800
  kill_delay = 500
  exclude_dir = ["tmp", "vendor", "cmd"]
  exclude_regex = ["_test\\.go"]
  exclude_unchanged = false
  include_dir = []
  include_ext = ["go", "env"]
  include_file = []
  log = "build-errors.log"
  send_interrupt = false
  stop_on_error = false

[color]
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = true

[screen]
  clear_on_rebuild = false
  keep_scroll = true
