root = "."
tmp_dir = "build"

[build]
bin = "./build/go-boilerplate-rest"
cmd = "make build-rest"
delay = 1000
rerun = true
rerun_delay = 80000
kill_delay = 500
exclude_dir = ["tmp", "vendor", "cmd", "docs", "internal/apps/rest/docs"]
exclude_regex = ["_test\\.go"]
exclude_unchanged = true
include_ext = ["go", "env"]
log = "build-errors.log"
stop_on_error = true

[color]
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
time = true

[misc]
clean_on_exit = true

[screen]
keep_scroll = true
