services:
  mariadb:
    container_name: go-boilerplate-mariadb
    image: mariadb:11
    restart: on-failure
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: rootAdmin123
      MYSQL_DATABASE: todolist
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 5s
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - ./.db/mariadb:/var/lib/mysql