services:
  mariadb:
    image: mariadb:11
    restart: on-failure
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: rootAdmin123
      MYSQL_DATABASE: todolist
    ports:
      - 3306:3306