services:
  mariadb:
    extends:
      file: docker-compose.db.yml
      service: mariadb
  app:
    extends:
      file: docker-compose.build.yml
      service: app
    depends_on:
      mariadb:
        condition: service_healthy
    environment:
      - ENVIRONMENT=production
      - MYSQL_HOST=mariadb