definitions:
  customerror.ErrorJSON:
    properties:
      message:
        type: string
      source_error_message:
        type: string
      stack:
        items:
          type: string
        type: array
    type: object
  dtos.AccountRegisterRequest:
    properties:
      email:
        type: string
      fullName:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
  models_mysql.Account:
    properties:
      createdAt:
        type: string
      deletedAt:
        type: string
      email:
        type: string
      fullName:
        type: string
      id:
        type: integer
      updatedAt:
        type: string
      username:
        type: string
    type: object
host: localhost:5000
info:
  contact: {}
  title: API documentation
  version: "1.0"
paths:
  /accounts:
    get:
      consumes:
      - application/json
      description: Gets all accounts along with its details
      parameters:
      - description: Account's username
        in: query
        name: username
        type: string
      - description: Account's email address
        in: query
        name: email
        type: string
      - description: Account's full name
        in: query
        name: fullName
        type: string
      - description: Limit the amount data to show
        in: query
        name: limit
        type: integer
      - description: The data offset, or where it should start
        in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models_mysql.Account'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/customerror.ErrorJSON'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/customerror.ErrorJSON'
      summary: Gets all accounts along with its details
      tags:
      - accounts
    post:
      consumes:
      - application/json
      description: Creates or registers a new account
      parameters:
      - description: New account details
        in: body
        name: newAccount
        required: true
        schema:
          $ref: '#/definitions/dtos.AccountRegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/customerror.ErrorJSON'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/customerror.ErrorJSON'
      summary: Register a new account
      tags:
      - accounts
  /accounts/{id}:
    get:
      consumes:
      - application/json
      description: Gets account details by the account ID
      parameters:
      - description: Account's ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models_mysql.Account'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/customerror.ErrorJSON'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/customerror.ErrorJSON'
      summary: Gets account details
      tags:
      - accounts
schemes:
- http
- https
swagger: "2.0"
